### ISSUE TITLE
FIX Dictionary

### ISSUE THREAD

**Issue by duncanesson** [yaalalabs/fixyl#12]
Hi, I am interested in this project, and potentially collaborating. Do you have a valid FIX 4.2 Dictionary file I can use as a starting point? I cannot seem to get any to load without exceptions. Thank you.

**Comment by DhananjayaR** [comment]
Please try https://github.com/quickfix/quickfix/blob/master/spec/FIX42.xml

**Comment by duncanesson** [comment]
Thanks
