### ISSUE TITLE
Quote request reject - incorrect UI / generation

### ISSUE THREAD

**Issue by dia-susca** [yaalalabs/fixyl#23]
For the Quote Request Reject <AG> message, the UI does not present the mandatory group 146 
`146 | NoRelatedSym | Y | Number of related symbols (instruments) in Request`

It shows the following components:
Group: NoQuoteQualifiers [735]

Component: SpreadOrBenchmarkCurveData
Component: YieldData
Component: Parties

**Comment by DhananjayaR** [comment]
To get a sense of the issue can you please provide the dictionary that you are using?

**Comment by dia-susca** [comment]
Sure. I use quickFix/J with a custom Fix 4.4 XML. I added a few custom fields that were needed, but did not alter message structure.
Please see the file, attached (renamed from .xml to .txt to make attachment work, but it's an XML file)

[FIX44_modified.txt](https://github.com/yaalalabs/fixyl/files/10426289/FIX44_modified.txt)

**Comment by DhananjayaR** [comment]
Issue fixed in https://github.com/yaalalabs/fixyl/releases/tag/v1.0.8

Please re-open if this re-creates again.
