### ISSUE TITLE
Message viewer: Subgroup Underlying Instrument not present in visual representation

### ISSUE THREAD

**Issue by dia-susca** [yaalalabs/fixyl#24]
Here is a sample of a FIX message that has underlying symbol information:

`8=FIX.4.4^9=316^35=R^34=45^49=XXXXXXXX^52=20230117-09:41:05.721^56=ENDPOINT^58=a repo req for ofrs^131=Q_RQ_REPO_1^1300=MktName^146=1^55=N/A^167=REPO^917=20230417^711=1^311=STCK^879=3000^537=1^54=2^38=5000^15=AZN^1=111000^581=3^44=2.5^453=3^448=YYYYYYYY^447=B^452=33^448=ZZZZZZZZ^447=B^452=33^448=KKKKKKKK^447=B^452=33^10=802^`

In message viewer, the visual representation of the message, the UnderlyingInstrument group information is not displayed. Interesting, however, that the FinancingDetails subgroup is shown.

**Comment by DhananjayaR** [comment]
Are you using the same dictionary file as in the previous issue?

**Comment by dia-susca** [comment]
yes, I am.

I am using as an alternate tool FixPusher, and that one  has no problem with the message structure as defined

**Comment by DhananjayaR** [comment]
Issue fixed in https://github.com/yaalalabs/fixyl/releases/tag/v1.0.8

Please re-open if this re-creates again.
