### ISSUE TITLE
Message viewer: Iterating sub-groups error

### ISSUE THREAD

**Issue by dia-susca** [yaalalabs/fixyl#25]
Sorry to be adding so many issues in such a short time, but I love this tool, and I've been using it a lot over the past few days.

Here is another problem I found.

Test message is a Security List message:
`8=FIX.4.4^9=291^35=y^34=9^49=ENDPOINT^52=20230118-11:35:21.406^56=XXXXXXXX^320=202301_2^322=4^560=0^146=2^55=BOND01^48=BOND01000006^22=4^461=DBFTFB^541=20230424^207=Mkt_1_Name^106=YYYYYYYY^107=ACTIVE^15=EUR^55=STCK^48=TESTSTOCKKK9^22=4^461=ESVTOB^207=Mkt_2_Name^106=ZZZZZZZZ^107=ACTIVE^15=EUR^10=116^
`
It retrieves a list of 2 distinct securities, yet the viewer displays the first one repeatedly:

![image](https://user-images.githubusercontent.com/30073490/213164514-f00236d3-bfd0-4a75-90f3-5a7c459716f9.png)

**Comment by DhananjayaR** [comment]
Issue fixed in https://github.com/yaalalabs/fixyl/releases/tag/v1.0.8

Please re-open if this re-creates again.
