### ISSUE TITLE
Support for {auto=gen} in DateTime field UI Element

### ISSUE THREAD

**Issue by GrumpyRoger** [yaalalabs/fixyl#31]
Currently you can't set {auto-gen} or manual DateTime value in TransactTime tag 60 ( example )

**Comment by DhananjayaR** [comment]
This is fixed in https://github.com/yaalalabs/fixyl/releases/tag/v1.0.9

**Comment by GrumpyRoger** [comment]
Unfortunately, DateFormat field is not accepting {auto-gen}, probably it needs to have separate generator for DateFormat fields, like "set current date and time"
