### ISSUE TITLE
Enable move Stage position in Scenarios

### ISSUE THREAD

**Issue by GrumpyRoger** [yaalalabs/fixyl#34]
Enhancement 
It would be great to have an option to move Stages inside Scenarios.
Currently adding New Stag in Scenario, places it at the bottom of the list, so it would be great to be able to move them or change their position in the Scenario.
That way we could have room for enhancements in existing Scenarios, by adding new Stage/Step in the middle of existing Scenario.

**Comment by DhananjayaR** [comment]
Good Idea. Will do it in the next release :)
