### ISSUE TITLE
Reading values "get" is failing without pointing to which value failed

### ISSUE THREAD

**Issue by GrumpyRoger** [yaalalabs/fixyl#37]
![image](https://user-images.githubusercontent.com/123978270/223110300-2b1ed4ce-4f06-4dea-a804-04e90956cf41.png)

**Comment by GrumpyRoger** [comment]
Looks like new release is broken in this function, when went back to R9 all works

**Comment by DhananjayaR** [comment]
This is fixed in v1.0.11
