### ISSUE TITLE
When editing or copying a profile with Fix Version Fix 5.X Transport Dictionary Location is not visible

### ISSUE THREAD

**Issue by rubaiate** [yaalalabs/fixyl#43]
Steps to reproduce.
1. Create a profile and set Fix Version to Fix 5.X.
2. Close profile
3. Open same profile for edit

Expected Result
Transport Dictionary Location should be visible

Actual Result
Transport Dictionary Location is not visible
![image](https://user-images.githubusercontent.com/7001376/235599032-fce32116-50d5-4372-9bb9-a0a477d6ff97.png)

**Comment by DhananjayaR** [comment]
This issue has been fixed in [v1.0.13](https://github.com/yaalalabs/fixyl/releases/tag/v1.0.13).  Let us know if you encounter any other issues.
