### ISSUE TITLE
Issue with Session and Global Parameters - Data Type = UTC Date Only

### ISSUE THREAD

**Issue by GrumpyRogerr** [yaalalabs/fixyl#46]
When creating new Parameter with Data Type Date, it hangs the app.
After refreshing/reloading, the parameter is there but in wrong format, example: 2023-10-03T08:45:45.813Z

**Comment by DhananjayaR** [comment]
We will check this out. Thanks for pointing it out.

**Comment by DhananjayaR** [comment]
This issue has been fixed in [v1.0.13](https://github.com/yaalalabs/fixyl/releases/tag/v1.0.13).  Let us know if you encounter any other issues.
