### ISSUE TITLE
Order of fields in repeating group

### ISSUE THREAD

**Issue by olivia-burca** [yaalalabs/fixyl#47]
Hello, i am trying to send a QuoteRequest message : 8=FIX.4.49=31135=R34=2049=ABBINVXXXXX52=20240315-07:55:24.03456=TS_NEG_GW115=ABBINVXXXXX116=4160258=Deal?131=QRQST11300=AZNNegoStckMain146=155=BAKAV167=REPO917=20230922711=1311=BAKAV879=18537=154=238=2015=AZN1=CD0000636102581=160=20240315-09:49:38.19444=2.1453=1448=ABBINVXXXXX447=B452=3310=226 , and I keep getting a reject with reason: The group 146 must set the delimiter field 55 (SessionRejectReason | REPEATING_GROUP_FIELDS_OUT_OF_ORDER [15]). I noticed that the order of the fields is changed in my message by fixyl : 8=FIX.4.49=31135=R34=8252=20240403-11:32:44.00049=ABBINVXXXXX56=TS_NEG_GW115=UNICAPXXXXX116=41651131=QRQST158=Deal ?1300=AZNNegoStckMain146=1537=154=215=AZN1=CD0000636102581=160=20240403-11:32:43.00044=2.1711=1311=BAKAV879=1855=BAKAV167=REPO917=2023092238=20453=1448=ABBINVXXXXX447=B452=3310=200
and thought maybe that might be the problem? i am using FIX 4.4. I saw the same issue reported #22 but it keeps happening for me. Thank you!

**Comment by DhananjayaR** [comment]
We will look into it. Please create more issues if you find any.

**Comment by DhananjayaR** [comment]
This issue has been fixed in [v1.0.13](https://github.com/yaalalabs/fixyl/releases/tag/v1.0.13).  Let us know if you encounter any other issues.
